var E = {
    DISCOVER_FEED: 5,
    DISCOVER_SEARCH: 30,
    DISCOVER_SQUARE: 20,
    DISCOVER_FEATURED: 20,
    DISCOVER_CONTRIBUTE: 20,
    DISCOVER_COMMENT: 20,
    DISCOVER_WEAK_FRIEND: 30,
    DISCOVER_DYNAMIC_FAVOR: 20,
    DISCOVER_FEED_MSG: 20,
    CLOUD_PHOTO: 30,
    FAVORITE_LIST: 10
};

module.exports = E;