Object.defineProperty(exports, "__esModule", {
    value: !0
});

var _ = function(_) {
    return "@dynamic/" + _;
}, A = {
    PUBLISH_DYNAMIC: _("PUBLISH_DYNAMIC"),
    UN_PUBLISH_DYNAMIC: _("UN_PUBLISH_DYNAMIC"),
    LIKE_DYNAMIC: _("LIKE_DYNAMIC"),
    UNLIKE_DYNAMIC: _("UNLIKE_DYNAMIC"),
    DELETE_DYNAMIC: _("DELETE_DYNAMIC"),
    ADD_DYNAMIC_COMMENT: _("ADD_DYNAMIC_COMMENT"),
    REMOVE_DYNAMIC_COMMENT: _("REMOVE_DYNAMIC_COMMENT"),
    FETCH_SINGLE_DYNAMIC: _("FETCH_SINGLE_DYNAMIC"),
    FETCH_ARTICLE_DETAIL: _("FETCH_ARTICLE_DETAIL"),
    UPDATE_SHARE_COUNT: _("UPDATE_SHARE_COUNT"),
    UPDATE_PLAY_COUNT: _("UPDATE_PLAY_COUNT"),
    COMPLAINT_DYNAMIC: _("COMPLAINT_DYNAMIC"),
    ADD_DYNAMIC_FAVORITES: _("ADD_DYNAMIC_FAVORITES"),
    DELETE_DYNAMIC_FAVORITES: _("DELETE_DYNAMIC_FAVORITES"),
    DELETE_DYNAMIC_FAVORITES_LIST: _("DELETE_DYNAMIC_FAVORITES_LIST"),
    FETCH_DYNAMIC_FAVORITES_LIST: _("FETCH_DYNAMIC_FAVORITES_LIST"),
    GET_DYNAMIC_IS_FAVORITES: _("GET_DYNAMIC_IS_FAVORITES"),
    CHANGE_SHOW_DYNAMIC_AUTHOR: _("CHANGE_SHOW_DYNAMIC_AUTHOR"),
    RENAME_DYNAMIC: _("RENAME_DYNAMIC"),
    UPDATE_DYNAMIC_STORY: _("UPDATE_DYNAMIC_STORY"),
    CHANGE_DYNAMIC_COVER: _("CHANGE_DYNAMIC_COVER"),
    RESTORE_DYNAMIC: _("RESTORE_DYNAMIC"),
    WIPE_DYNAMIC: _("WIPE_DYNAMIC"),
    COMMIT_DYNAMIC: _("COMMIT_DYNAMIC"),
    MODIFY_DYNAMIC: _("MODIFY_DYNAMIC"),
    UPDATE_DYNAMIC: _("UPDATE_DYNAMIC"),
    GET_DYNAMIC_TPL_MUSIC: _("GET_DYNAMIC_TPL_MUSIC")
};

exports.default = A;