Object.defineProperty(exports, "__esModule", {
    value: !0
});

var E = function(E) {
    return "@dynamic/" + E;
};

exports.FETCH_FEED = E("FETCH_FEED"), exports.CLEAR_FEED = E("CLEAR_FEED"), exports.FETCH_FEED_RECOMMEND = E("FETCH_FEED_RECOMMEND"), 
exports.CLEAR_FEED_RECOMMEND = E("CLEAR_FEED_RECOMMEND"), exports.INSERT_TO_DISCOVER_RECOMMEND = E("INSERT_TO_DISCOVER_RECOMMEND"), 
exports.FETCH_WEAK_FRIEND = E("FETCH_WEAK_FRIEND"), exports.FETCH_DYNAMIC_COMMENT = E("FETCH_DYNAMIC_COMMENT"), 
exports.CLEAR_DYNAMIC_COMMENT = E("CLEAR_DYNAMIC_COMMENT"), exports.LIKE_DYNAMIC_COMMENT = E("LIKE_DYNAMIC_COMMENT"), 
exports.CANCEL_LIKE_DYNAMIC_COMMENT = E("CANCEL_LIKE_DYNAMIC_COMMENT"), exports.FOLLOW_USER = E("FOLLOW_USER"), 
exports.UNFOLLOW_USER = E("UNFOLLOW_USER"), exports.FETCH_DYNAMIC_FAVOR_USER = E("FETCH_DYNAMIC_FAVOR_USER"), 
exports.CLEAR_DYNAMIC_FAVOR_USER = E("CLEAR_DYNAMIC_FAVOR_USER"), exports.FETCH_DYNAMIC_MESSAGE = E("FETCH_DYNAMIC_MESSAGE"), 
exports.CLEAR_UNREAD_DYNAMIC_MESSAGE = E("CLEAR_UNREAD_DYNAMIC_MESSAGE"), exports.SEE_EARLIER_DYNAMIC_MESSAGE = E("SEE_EARLIER_DYNAMIC_MESSAGE"), 
exports.RESET_DYNAMIC_MESSAGE = E("RESET_DYNAMIC_MESSAGE"), exports.FETCH_IF_CAN_MAKE_SAME = E("FETCH_IF_CAN_MAKE_SAME"), 
exports.SAVE_ALBUM_MUSIC = E("SAVE_ALBUM_MUSIC"), exports.SET_CUR_DYNAMIC_COMMENT = E("SET_CUR_DYNAMIC_COMMENT"), 
exports.CLEAR_CUR_DYNAMIC_COMMENT = E("CLEAR_CUR_DYNAMIC_COMMENT"), exports.LOG_PLAY_UV = E("LOG_PLAY_UV"), 
exports.LOG_VIEW = E("LOG_VIEW"), exports.LOG_SHARE = E("LOG_SHARE");